name: A cron job named Khronos

on:
  schedule:
    - cron: '38 2,14 * * *'
  workflow_dispatch:
    # Nada

jobs:
  commit-a-change:
    runs-on: ubuntu-latest # aka orange windows

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: 24f3004990@ds.study.iitm.ac.in
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          head -n 4 /dev/urandom | base64 > proof-of-work
          git add proof-of-work
          git commit -m "wow this works" || exit 0
          git push
